#ifndef _APP_CFG_H
#define _APP_CFG_H

#define TASK_START_PRIO      		1

#define TASK_FUNCTION_PRIO   	    9
#define TASK_LOGIC_PRIO			 	8
#define	TASK_MMI_PRIO				7

#define	TASK_COMM1_RECE_PRIO		4	
#define	TASK_COMM2_RECE_PRIO		5
#define	TASK_COMM3_RECE_PRIO		6
//#define	TASK_COMM1_SEND_PRIO		10
//#define	TASK_COMM2_SEND_PRIO		11
//#define	TASK_COMM3_SEND_PRIO		12

#define OS_TASK_TMR_PRIO           (OS_LOWEST_PRIO - 2)

#define TASK_START_STK_SIZE         512

#define TASK_FUNCTION_STK_SIZE      1024
#define TASK_LOGIC_STK_SIZE			1024
#define	TASK_MMI_STK_SIZE	  		1024

#define	TASK_COMM1_RECE_STK_SIZE    2048
#define	TASK_COMM2_RECE_STK_SIZE    2048
#define	TASK_COMM3_RECE_STK_SIZE    2048
//#define TASK_COMM1_SEND_STK_SIZE    1024
//#define TASK_COMM2_SEND_STK_SIZE    1024
//#define TASK_COMM3_SEND_STK_SIZE    1024

#endif

